baseURL = 'https://biologicinfo.github.io/rjevolution'
languageCode = 'it-it'
DefaultContentLanguage = "it"
title = 'Etica ed Evoluzione del Ringiovanimento'
theme = "ananke"
googleAnalytics = "G-H41E1B9G7L"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  recent_posts_number = 3


[[menu.main]]
name = "About"
weight = 0
identifier = "about" # this button will refer to a markdown file named "about" in the content folder
pre = "<br />"
url = "/pages/about"

[[menu.main]]
name = "News"
weight = 0
identifier = "news" # this button will refer to a markdown file named "news" in the content folder
pre = "<br />"
url = "/pages/news"

[[menu.main]]
name = "Pagine"
weight = 0
identifier = "pages" # this button will refer to a markdown file named "news" in the content folder
pre = "<br />"
url = "/pages"

[[menu.main]]
name = "Papers"
weight = 0
identifier = "papers" # this button will refer to a markdown file named "papers" in the content folder
pre = "<br />"
url = "/papers"
